site_name: "Vib⊕arth"
site_url: https://vibearth.dev
site_description: Think Earth, Make Earth.
site_author: Lee Heunggi

theme:
  name: material
  language: ko
  icon:
    logo: fontawesome/solid/earth-asia
  palette:
    scheme: slate
    primary: teal
    accent: teal
  font:
    text: Noto Sans KR
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.top
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VibEarth
    - icon: fontawesome/solid/earth-asia
      link: https://vibearth.dev
      name: Vibearth
  analytics:
    provider: google
    property: G-CEZKH5YMXY

plugins:
  - search
  - roamlinks

nav:
  - Home: index.md
  - ESP32 Project:
    - Intro: esp32/intro.md
    - I. ESP32-C3 SuperMini:
      - Settings: esp32/c3/settings.md
      - Hello,LED: esp32/c3/led.md
      - BME280 sensor: esp32/c3/bme280.md
    - Appendix: 
      - A. Sensors Comparison: esp32/c3/appendix_A.md
      # - Modules:
      #   - RGB_LED: esp32/c3/rgb_led.md
      #   - BME280: esp32/c3/bme280.md
      # - Weather Station: esp32/c3/weather_station.md
    # - II. XIAO ESP32-S3:
    #   - Settings: esp32/s3/setup.md
    #   - Weather Drone: esp32/s3/weather_drone.md
