site_name: Vib⊕arth
site_url: https://vibearth.dev
site_description: Think Earth, Make Earth.
site_author: Lee Heunggi

theme:
  name: material
  language: ko
  icon:
    logo: fontawesome/solid/earth-asia
  palette:
    scheme: slate
    primary: teal
    accent: teal
  font:
    text: Noto Sans KR
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VibEarth
    - icon: fontawesome/solid/earth-asia
      link: https://vibearth.dev
      name: Vibearth

nav:
  - Home: index.md
  - ESP32 Project:
    - Intro: esp32/intro.md
    # - Settings: esp32/setup.md
    # - Modules:
    #   - RGB_LED: esp32/sensors/rgb_led.md
    #   - BME280: esp32/sensors/bme280.md
    #   - (더 추가 예정): esp32/sensors/index.md
    # - ESP32 Weather Station: esp32/weather_station.md
    # - ESP32 Weather Drone: esp32/weather_drone.md
